import AVFoundation
import Foundation
import MagentaRT

/// Lock-free audio level meter: the realtime render thread writes the per-block
/// RMS, the UI reads it. arm64 aligned 32-bit loads/stores are atomic and a
/// torn-free *stale* read of a meter value is harmless, so we avoid taking any
/// lock on the audio thread. (`Synchronization.Atomic` would need macOS 15; this
/// target is macOS 14.)
public final class LevelMeter: @unchecked Sendable {
    private nonisolated(unsafe) var rmsBits: UInt32 = 0
    /// Linear RMS of the most recent render block (~0…1).
    public var rms: Float { Float(bitPattern: rmsBits) }
    @inline(__always) func store(_ v: Float) { rmsBits = v.bitPattern }
}

/// Realtime player: streams audio generated by `RealtimeEngine` through an
/// `AVAudioEngine` source node.
///
/// Concurrency boundary (the crux of the design):
///  - Lifecycle and prompt changes go through the `RealtimeEngine` actor.
///  - The `AVAudioSourceNode` render block is **nonisolated** and runs on the
///    CoreAudio render thread. It calls `RealtimeRenderHandle.read` directly —
///    no `await`, no allocation, no actor hop.
///  - Ordering invariant enforced here: `start()` starts the inference loop
///    BEFORE the audio engine; `stop()` stops the audio engine BEFORE the
///    inference loop. So a render call can never race lifecycle teardown.
@MainActor
public final class MagentaPlayer {
    private let engine: RealtimeEngine
    private let avEngine = AVAudioEngine()
    private let format = AVAudioFormat(standardFormatWithSampleRate:
                                        Double(MagentaRTConstants.sampleRate),
                                       channels: 2)!
    private var sourceNode: AVAudioSourceNode?
    private var renderHandle: RealtimeRenderHandle?

    public private(set) var controls: RealtimeControls?
    public private(set) var isRunning = false

    /// Live output level (updated on the audio thread; poll from the UI).
    public let meter = LevelMeter()

    public init() {
        self.engine = RealtimeEngine()
    }

    // MARK: Setup

    public func load(model: String, resources: String) async throws {
        try await engine.initAssets(resourceDir: resources)
        try await engine.loadModel(model)
        controls = await engine.makeControls()
    }

    public func setPrompt(_ text: String) async throws {
        try await engine.setTextPrompt(text)
    }

    /// Set several weighted prompts; blend between them live via
    /// `controls.setBlendWeights(_:)`.
    public func setPrompts(_ prompts: [(text: String, weight: Float)]) async throws {
        try await engine.setPrompts(prompts)
    }

    // MARK: Transport

    /// Build the audio graph, start the inference loop, then start audio.
    public func start() async throws {
        guard !isRunning else { return }

        let handle = await engine.makeRenderHandle()
        renderHandle = handle

        // Build the source node in a NONISOLATED context. If the render closure
        // were created here (inside this @MainActor method) it would inherit
        // MainActor isolation, and CoreAudio invoking it on the audio thread
        // would trip `swift_task_checkIsolated` → dispatch_assert_queue(main) →
        // crash. `makeSourceNode` is nonisolated, so the closure is too.
        let node = Self.makeSourceNode(format: format, handle: handle, meter: meter)
        sourceNode = node
        avEngine.attach(node)
        avEngine.connect(node, to: avEngine.mainMixerNode, format: format)

        // Inference loop first so the ring buffers prime before audio pulls.
        await engine.start()
        avEngine.prepare()
        try avEngine.start()
        isRunning = true
    }

    /// Stop audio first (no more render calls), then the inference loop.
    public func stop() async {
        guard isRunning else { return }
        avEngine.stop()
        if let node = sourceNode {
            avEngine.detach(node)
            sourceNode = nil
        }
        await engine.stop()
        renderHandle = nil
        isRunning = false
    }

    /// Build the `AVAudioSourceNode`. **`nonisolated`** so the render closure
    /// it creates is not MainActor-isolated — it runs on the realtime CoreAudio
    /// render thread. The closure touches only `handle` (`@unchecked Sendable`),
    /// performs no allocation, no `await`, and no actor hop.
    nonisolated private static func makeSourceNode(
        format: AVAudioFormat,
        handle: RealtimeRenderHandle,
        meter: LevelMeter
    ) -> AVAudioSourceNode {
        AVAudioSourceNode(format: format) { _, _, frameCount, audioBufferList in
            let abl = UnsafeMutableAudioBufferListPointer(audioBufferList)
            let frames = Int(frameCount)
            guard abl.count >= 2,
                  let lRaw = abl[0].mData,
                  let rRaw = abl[1].mData
            else {
                // Unexpected layout — emit silence, never stale memory (noise).
                for b in abl { if let d = b.mData { memset(d, 0, Int(b.mDataByteSize)) } }
                return noErr
            }
            let l = lRaw.assumingMemoryBound(to: Float.self)
            let r = rRaw.assumingMemoryBound(to: Float.self)
            _ = handle.read(l, r, frames)
            // Soft-safety clamp to [-1, 1] (prevents harsh clipping on rare
            // generative transients) + per-block RMS for the meter.
            if frames > 0 {
                var sum: Float = 0
                for i in 0..<frames {
                    let lv = min(1, max(-1, l[i])); l[i] = lv
                    let rv = min(1, max(-1, r[i])); r[i] = rv
                    let m = (lv + rv) * 0.5; sum += m * m
                }
                meter.store((sum / Float(frames)).squareRoot())
            }
            return noErr
        }
    }

    // MARK: Metrics

    public func metrics() async -> RealtimeEngine.Metrics {
        await engine.metrics()
    }
}
